package business

import mock "github.com/stretchr/testify/mock"

// SwapiInterfaceMock is an autogenerated mock type for the SwapiInterfaceMock type
type SwapiInterfaceMock struct {
	mock.Mock
}

// GetMoviesCount provides a mock function with given fields: planet
func (_m *SwapiInterfaceMock) GetMoviesCount(planet Planet) (int, error) {
	ret := _m.Called(planet)

	var r0 int
	if rf, ok := ret.Get(0).(func(Planet) int); ok {
		r0 = rf(planet)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Planet) error); ok {
		r1 = rf(planet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
